In [8]:
import pandas as pd
import numpy as np

train_data = pd.read_csv("train.csv")

# Age NA -> Median of Age
median_age_train = train_data["Age"].median()
train_data["Age"] = train_data["Age"].fillna(median_age_train)

# Embarked NA -> Mode of Embarked
mst_frq_embarked_train = train_data["Embarked"].value_counts().index[0]
train_data["Embarked"] = train_data["Embarked"].fillna(mst_frq_embarked_train)

# Embarked dtypte -> int
Ports = list(enumerate(np.unique(train_data['Embarked'])))
Ports_dict = { name : i for i, name in Ports }
train_data["Embarked"] = train_data["Embarked"].map(lambda x: Ports_dict[x]).astype(int)

# New Gender Column {male:1, female:0}
train_data["Gender"] = 0
train_data["Gender"][train_data["Sex"] == 'male'] = 1

train_data.head()
# train_data.info()
# train_data.describe()

C:\Users\kjh43\Anaconda3\lib\site-packages\ipykernel\__main__.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Gender
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,2,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,0,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,2,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,2,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,2,1

In [9]:
test_data = pd.read_csv("test.csv")

# Age NA -> Median of Age
median_age_test = test_data["Age"].median()
test_data["Age"] = test_data["Age"].fillna(median_age_test)

# Embarked NA -> Mode of Embarked
mst_frq_embarked_test = test_data["Embarked"].value_counts().index[0]
test_data["Embarked"] = test_data["Embarked"].fillna(mst_frq_embarked_test)

# Embarked dtypte -> int
test_data["Embarked"] = test_data["Embarked"].map(lambda x: Ports_dict[x]).astype(int)

# New Gender Column {male:1, female:0}
test_data["Gender"] = 0
test_data["Gender"][test_data["Sex"] == 'male'] = 1

# Fare NA -> Median of Fare
test_data["Fare"] = test_data["Fare"].fillna(test_data["Fare"].median())

test_data["Survived"] = np.NaN

test_data.head()
test_data.info()
test_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 13 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null object
Age            418 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           418 non-null float64
Cabin          91 non-null object
Embarked       418 non-null int32
Gender         418 non-null int64
Survived       0 non-null float64
dtypes: float64(3), int32(1), int64(5), object(4)
memory usage: 40.9+ KB

C:\Users\kjh43\Anaconda3\lib\site-packages\ipykernel\__main__.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\kjh43\Anaconda3\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Embarked,Gender,Survived
count,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,0.0
mean,1100.500000,2.265550,29.599282,0.447368,0.392344,35.576535,1.401914,0.636364,NaN
std,120.810458,0.841838,12.703770,0.896760,0.981429,55.850103,0.854496,0.481622,NaN
min,892.000000,1.000000,0.170000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,996.250000,1.000000,23.000000,0.000000,0.000000,7.895800,1.000000,0.000000,NaN
50%,1100.500000,3.000000,27.000000,0.000000,0.000000,14.454200,2.000000,1.000000,NaN
75%,1204.750000,3.000000,35.750000,1.000000,0.000000,31.471875,2.000000,1.000000,NaN
max,1309.000000,3.000000,76.000000,8.000000,9.000000,512.329200,2.000000,1.000000,NaN

In [4]:
X_train = train_data[["Pclass", "Gender", "Age", "Fare", "Embarked", "SibSp", "Parch"]]
y_train = train_data["Survived"]

X_test = test_data[["Pclass", "Gender", "Age", "Fare", "Embarked", "SibSp", "Parch"]]
y_test = test_data["Survived"]

X_train = X_train.astype("float")
X_train

     Pclass  Gender   Age      Fare  Embarked  SibSp  Parch
0       3.0     1.0  22.0    7.2500       2.0    1.0    0.0
1       1.0     0.0  38.0   71.2833       0.0    1.0    0.0
2       3.0     0.0  26.0    7.9250       2.0    0.0    0.0
3       1.0     0.0  35.0   53.1000       2.0    1.0    0.0
4       3.0     1.0  35.0    8.0500       2.0    0.0    0.0
5       3.0     1.0  28.0    8.4583       1.0    0.0    0.0
6       1.0     1.0  54.0   51.8625       2.0    0.0    0.0
7       3.0     1.0   2.0   21.0750       2.0    3.0    1.0
8       3.0     0.0  27.0   11.1333       2.0    0.0    2.0
9       2.0     0.0  14.0   30.0708       0.0    1.0    0.0
10      3.0     0.0   4.0   16.7000       2.0    1.0    1.0
11      1.0     0.0  58.0   26.5500       2.0    0.0    0.0
12      3.0     1.0  20.0    8.0500       2.0    0.0    0.0
13      3.0     1.0  39.0   31.2750       2.0    1.0    5.0
14      3.0     0.0  14.0    7.8542       2.0    0.0    0.0
15      2.0     0.0  55.0   16.0000       2.0    0.0    0.0
16      3.0     1.0   2.0   29.1250       1.0    4.0    1.0
17      2.0     1.0  28.0   13.0000       2.0    0.0    0.0
18      3.0     0.0  31.0   18.0000       2.0    1.0    0.0
19      3.0     0.0  28.0    7.2250       0.0    0.0    0.0
20      2.0     1.0  35.0   26.0000       2.0    0.0    0.0
21      2.0     1.0  34.0   13.0000       2.0    0.0    0.0
22      3.0     0.0  15.0    8.0292       1.0    0.0    0.0
23      1.0     1.0  28.0   35.5000       2.0    0.0    0.0
24      3.0     0.0   8.0   21.0750       2.0    3.0    1.0
25      3.0     0.0  38.0   31.3875       2.0    1.0    5.0
26      3.0     1.0  28.0    7.2250       0.0    0.0    0.0
27      1.0     1.0  19.0  263.0000       2.0    3.0    2.0
28      3.0     0.0  28.0    7.8792       1.0    0.0    0.0
29      3.0     1.0  28.0    7.8958       2.0    0.0    0.0
..      ...     ...   ...       ...       ...    ...    ...
861     2.0     1.0  21.0   11.5000       2.0    1.0    0.0
862     1.0     0.0  48.0   25.9292       2.0    0.0    0.0
863     3.0     0.0  28.0   69.5500       2.0    8.0    2.0
864     2.0     1.0  24.0   13.0000       2.0    0.0    0.0
865     2.0     0.0  42.0   13.0000       2.0    0.0    0.0
866     2.0     0.0  27.0   13.8583       0.0    1.0    0.0
867     1.0     1.0  31.0   50.4958       2.0    0.0    0.0
868     3.0     1.0  28.0    9.5000       2.0    0.0    0.0
869     3.0     1.0   4.0   11.1333       2.0    1.0    1.0
870     3.0     1.0  26.0    7.8958       2.0    0.0    0.0
871     1.0     0.0  47.0   52.5542       2.0    1.0    1.0
872     1.0     1.0  33.0    5.0000       2.0    0.0    0.0
873     3.0     1.0  47.0    9.0000       2.0    0.0    0.0
874     2.0     0.0  28.0   24.0000       0.0    1.0    0.0
875     3.0     0.0  15.0    7.2250       0.0    0.0    0.0
876     3.0     1.0  20.0    9.8458       2.0    0.0    0.0
877     3.0     1.0  19.0    7.8958       2.0    0.0    0.0
878     3.0     1.0  28.0    7.8958       2.0    0.0    0.0
879     1.0     0.0  56.0   83.1583       0.0    0.0    1.0
880     2.0     0.0  25.0   26.0000       2.0    0.0    1.0
881     3.0     1.0  33.0    7.8958       2.0    0.0    0.0
882     3.0     0.0  22.0   10.5167       2.0    0.0    0.0
883     2.0     1.0  28.0   10.5000       2.0    0.0    0.0
884     3.0     1.0  25.0    7.0500       2.0    0.0    0.0
885     3.0     0.0  39.0   29.1250       1.0    0.0    5.0
886     2.0     1.0  27.0   13.0000       2.0    0.0    0.0
887     1.0     0.0  19.0   30.0000       2.0    0.0    0.0
888     3.0     0.0  28.0   23.4500       2.0    1.0    2.0
889     1.0     1.0  26.0   30.0000       0.0    0.0    0.0
890     3.0     1.0  32.0    7.7500       1.0    0.0    0.0

[891 rows x 7 columns]

In [ ]:
import tensorflow as tf


# xy = np.loadtxt('07train.txt', unpack=True) 
x_data = np.array(X_train, dtype=np.float32) 
y_data = np.reshape(np.array(train_data["Survived"], dtype=np.float32), (891,1))
# y_data =np.array(train_data["Survived"], dtype=np.float32)

x_data_test = np.array(X_test, dtype=np.float32)

# print (x_data) 
# print (y_data) 

X = tf.placeholder(tf.float32, name="X-input")
Y = tf.placeholder(tf.float32, name="Y-input")

# Wide network: Use more neurons in each layer. 
W1 = tf.Variable(tf.random_uniform( [7,10], -1.0, 1.0), name="weight1")
W2 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight2")
W3 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight3")
W4 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight4")
W5 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight5")
W6 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight6")
W7 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight7")
W8 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight8")
W9 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight9")
W10 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight10")
W11 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight11")
W12 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight12")
W13 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight13")
W14 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight14")
W15 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight15")
W16 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight16")
W17 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight17")
W18 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight18")
W19 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight19")
W20 = tf.Variable(tf.random_uniform( [10,10], -1.0, 1.0), name="weight20")

W21 = tf.Variable(tf.random_uniform( [10,1], -1.0, 1.0), name="weight21")

b1 = tf.Variable(tf.zeros([10]), name="bias1")
b2 = tf.Variable(tf.zeros([10]), name="bias2")
b3 = tf.Variable(tf.zeros([10]), name="bias3")
b4 = tf.Variable(tf.zeros([10]), name="bias4")
b5 = tf.Variable(tf.zeros([10]), name="bias5")
b6 = tf.Variable(tf.zeros([10]), name="bias6")
b7 = tf.Variable(tf.zeros([10]), name="bias7")
b8 = tf.Variable(tf.zeros([10]), name="bias8")
b9 = tf.Variable(tf.zeros([10]), name="bias9")
b10 = tf.Variable(tf.zeros([10]), name="bias10")
b11 = tf.Variable(tf.zeros([10]), name="bias11")
b12 = tf.Variable(tf.zeros([10]), name="bias12")
b13 = tf.Variable(tf.zeros([10]), name="bias13")
b14 = tf.Variable(tf.zeros([10]), name="bias14")
b15 = tf.Variable(tf.zeros([10]), name="bias15")
b16 = tf.Variable(tf.zeros([10]), name="bias16")
b17 = tf.Variable(tf.zeros([10]), name="bias17")
b18 = tf.Variable(tf.zeros([10]), name="bias18")
b19 = tf.Variable(tf.zeros([10]), name="bias19")
b20 = tf.Variable(tf.zeros([10]), name="bias20")

b21 = tf.Variable(tf.zeros([1]), name="bias21")

# Hypotheses 
with tf.name_scope("layer2") as scope:
    L2 =  tf.nn.relu(tf.matmul(X,W1)+b1)

with tf.name_scope("layer3") as scope:    
    L3 =  tf.nn.relu(tf.matmul(L2,W2)+b2)
    
with tf.name_scope("layer4") as scope:    
    L4 =  tf.nn.relu(tf.matmul(L3,W3)+b3)
    
with tf.name_scope("layer5") as scope:    
    L5 =  tf.nn.relu(tf.matmul(L4,W4)+b4)
    
with tf.name_scope("layer6") as scope:    
    L6 =  tf.nn.relu(tf.matmul(L5,W5)+b5)
    
with tf.name_scope("layer7") as scope:    
    L7 =  tf.nn.relu(tf.matmul(L6,W6)+b6)

with tf.name_scope("layer8") as scope:    
    L8 =  tf.nn.relu(tf.matmul(L7,W7)+b7)
    
with tf.name_scope("layer9") as scope:    
    L9 =  tf.nn.relu(tf.matmul(L8,W8)+b8)
    
with tf.name_scope("layer10") as scope:    
    L10 =  tf.nn.relu(tf.matmul(L9,W9)+b9)
    
with tf.name_scope("layer11") as scope:    
    L11 =  tf.nn.relu(tf.matmul(L10,W10)+b10)
    
with tf.name_scope("layer12") as scope:    
    L12 =  tf.nn.relu(tf.matmul(L11,W11)+b11)
    
with tf.name_scope("layer13") as scope:    
    L13 =  tf.nn.relu(tf.matmul(L12,W12)+b12)
    
with tf.name_scope("layer14") as scope:    
    L14 =  tf.nn.relu(tf.matmul(L13,W13)+b13)
    
with tf.name_scope("layer15") as scope:    
    L15 =  tf.nn.relu(tf.matmul(L14,W14)+b14)
    
with tf.name_scope("layer16") as scope:    
    L16 =  tf.nn.relu(tf.matmul(L15,W15)+b15)
    
with tf.name_scope("layer17") as scope:    
    L17 =  tf.nn.relu(tf.matmul(L16,W16)+b16)
    
with tf.name_scope("layer18") as scope:    
    L18 =  tf.nn.relu(tf.matmul(L17,W17)+b17)
    
with tf.name_scope("layer19") as scope:    
    L19 =  tf.nn.relu(tf.matmul(L18,W18)+b18)
    
with tf.name_scope("layer20") as scope:    
    L20 =  tf.nn.relu(tf.matmul(L19,W19)+b19)
    
with tf.name_scope("layer21") as scope:    
    L21 =  tf.nn.relu(tf.matmul(L20,W20)+b20)
    
with tf.name_scope("layer22") as scope:
    hypothesis = tf.sigmoid( tf.matmul(L21,W21) + b21)

# Cost function 
with tf.name_scope("cost") as scope:
    cost = -tf.reduce_mean( Y*tf.log(hypothesis)+(1-Y)* tf.log(1.-hypothesis) )

# Minimize cost.
a = tf.Variable(0.1)
with tf.name_scope("train") as scope:
    optimizer = tf.train.GradientDescentOptimizer(a)
    train = optimizer.minimize(cost)

# Initializa all variables.
init = tf.initialize_all_variables()


# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(50001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        
        if step % 1000 == 0:
            print(
                step, 
                sess.run(cost, feed_dict={X:x_data, Y:y_data}), 
                sess.run(W1),
                sess.run(W2)
            )
    
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis+0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print( sess.run( [hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy], 
                   feed_dict={X:x_data, Y:y_data}) )
    print( "Accuracy:", accuracy.eval({X:x_data, Y:y_data}) )
    
    # Predict
    predict = sess.run(tf.floor(hypothesis+0.5), feed_dict={X:x_data_test})
    print(predict)

WARNING:tensorflow:From <ipython-input-7-a4205c28e069>:139 in <module>.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
0 0.767979 [[-0.43925953  0.39654946  0.75850129  0.46155906  0.49158907 -0.73411608
   0.92117572  0.14414692  0.19505286  0.56225944]
 [-0.19095635 -0.47052455 -0.07899547  0.92174292  0.37236238 -0.03722787
   0.9969368  -0.49113226 -0.28499675  0.12402487]
 [-0.89337802  0.52696347  0.97484517  0.90222621  0.33551431 -0.60604048
   0.78848886 -0.8544662   0.05395889  0.98471951]
 [-0.41830897 -0.83323026  0.55251837 -0.02732611 -0.98443961  0.74806094
  -0.9536221   0.60010004  0.58222556 -0.11899447]
 [-0.19168067  0.31838632 -0.55445719  0.15315843 -0.64731288  0.95715165
  -0.5809834  -0.17919064  0.66809273 -0.38952017]
 [ 0.08074236  0.77345085 -0.82865477 -0.12224722  0.24851894  0.49926257
  -0.93379998 -0.67235923  0.71380305 -0.40337038]
 [ 0.58041739 -0.16755199  0.75980902  0.52284431 -0.77832699  0.56391907
  -0.65236187  0.03742433  0.19807673 -0.86889815]] [[ 0.03844428 -0.61687589  0.77105546 -0.53429389  0.43078113 -0.51339889
  -0.86045003 -0.12740755 -0.53186226 -0.04335356]
 [ 0.64824319  0.3808291  -0.87813687 -0.28606343  0.7092855   0.30556369
  -0.37343311  0.19230628  0.91141629 -0.99441814]
 [ 0.76022744 -0.01165318 -0.79493237  0.41822076  0.51319218  0.32334471
   0.98885846  0.11100173 -0.85208106  0.26295304]
 [-0.71011019 -0.9679718  -0.32678986  0.36189032 -0.71350431 -0.63158751
   0.76638818  0.23931861 -0.37095833 -0.84048557]
 [-0.55133247  0.53780198 -0.67556119 -0.12662482  0.02922988 -0.96926141
   0.67065406  0.82795072 -0.41323805 -0.7376678 ]
 [ 0.05176353 -0.8381753  -0.79019547  0.37744546 -0.56018686  0.69880033
  -0.2369802   0.2512114   0.76013947  0.42092705]
 [ 0.29867768  0.3647089  -0.08300138 -0.56301904  0.16217613 -0.24444103
  -0.07246351 -0.4804852   0.25434518 -0.6795969 ]
 [-0.33194089  0.87319827  0.2266233   0.97883606  0.95746088 -0.99121714
   0.60725546 -0.2594831   0.77461576  0.25920606]
 [-0.64279556  0.13874698  0.56704402  0.19232464 -0.66687822 -0.00693417
  -0.16051269  0.76022243  0.24708843 -0.82646346]
 [ 0.18449402  0.33861756  0.16553259  0.60852623 -0.10023761  0.72201872
  -0.5360527   0.74935722  0.28408647  0.87149811]]
1000 0.665913 [[-0.43925953  0.39654946  0.75850129  0.46155906  0.49158907 -0.73411608
   0.92117572  0.14414692  0.19505286  0.56225944]
 [-0.19095635 -0.47052455 -0.07899547  0.92174292  0.37236238 -0.03722787
   0.9969368  -0.49113226 -0.28499675  0.12402487]
 [-0.89337802  0.52696347  0.97484517  0.90222621  0.33551431 -0.60604048
   0.78848886 -0.8544662   0.05395889  0.98471951]
 [-0.41830897 -0.83323026  0.55251837 -0.02732611 -0.98443961  0.74806094
  -0.9536221   0.60010004  0.58222556 -0.11899447]
 [-0.19168067  0.31838632 -0.55445719  0.15315843 -0.64731288  0.95715165
  -0.5809834  -0.17919064  0.66809273 -0.38952017]
 [ 0.08074236  0.77345085 -0.82865477 -0.12224722  0.24851894  0.49926257
  -0.93379998 -0.67235923  0.71380305 -0.40337038]
 [ 0.58041739 -0.16755199  0.75980902  0.52284431 -0.77832699  0.56391907
  -0.65236187  0.03742433  0.19807673 -0.86889815]] [[ 0.03844428 -0.61687589  0.77105546 -0.53429389  0.43078113 -0.51339889
  -0.86045003 -0.12740755 -0.53186226 -0.04335356]
 [ 0.64824319  0.3808291  -0.87813687 -0.28606343  0.7092855   0.30556369
  -0.37343311  0.19230628  0.91141629 -0.99441814]
 [ 0.76022744 -0.01165318 -0.79493237  0.41822076  0.51319218  0.32334471
   0.98885846  0.11100173 -0.85208106  0.26295304]
 [-0.71011019 -0.9679718  -0.32678986  0.36189032 -0.71350431 -0.63158751
   0.76638818  0.23931861 -0.37095833 -0.84048557]
 [-0.55133247  0.53780198 -0.67556119 -0.12662482  0.02922988 -0.96926141
   0.67065406  0.82795072 -0.41323805 -0.7376678 ]
 [ 0.05176353 -0.8381753  -0.79019547  0.37744546 -0.56018686  0.69880033
  -0.2369802   0.2512114   0.76013947  0.42092705]
 [ 0.29867768  0.3647089  -0.08300138 -0.56301904  0.16217613 -0.24444103
  -0.07246351 -0.4804852   0.25434518 -0.6795969 ]
 [-0.33194089  0.87319827  0.2266233   0.97883606  0.95746088 -0.99121714
   0.60725546 -0.2594831   0.77461576  0.25920606]
 [-0.64279556  0.13874698  0.56704402  0.19232464 -0.66687822 -0.00693417
  -0.16051269  0.76022243  0.24708843 -0.82646346]
 [ 0.18449402  0.33861756  0.16553259  0.60852623 -0.10023761  0.72201872
  -0.5360527   0.74935722  0.28408647  0.87149811]]
2000 0.665913 [[-0.43925953  0.39654946  0.75850129  0.46155906  0.49158907 -0.73411608
   0.92117572  0.14414692  0.19505286  0.56225944]
 [-0.19095635 -0.47052455 -0.07899547  0.92174292  0.37236238 -0.03722787
   0.9969368  -0.49113226 -0.28499675  0.12402487]
 [-0.89337802  0.52696347  0.97484517  0.90222621  0.33551431 -0.60604048
   0.78848886 -0.8544662   0.05395889  0.98471951]
 [-0.41830897 -0.83323026  0.55251837 -0.02732611 -0.98443961  0.74806094
  -0.9536221   0.60010004  0.58222556 -0.11899447]
 [-0.19168067  0.31838632 -0.55445719  0.15315843 -0.64731288  0.95715165
  -0.5809834  -0.17919064  0.66809273 -0.38952017]
 [ 0.08074236  0.77345085 -0.82865477 -0.12224722  0.24851894  0.49926257
  -0.93379998 -0.67235923  0.71380305 -0.40337038]
 [ 0.58041739 -0.16755199  0.75980902  0.52284431 -0.77832699  0.56391907
  -0.65236187  0.03742433  0.19807673 -0.86889815]] [[ 0.03844428 -0.61687589  0.77105546 -0.53429389  0.43078113 -0.51339889
  -0.86045003 -0.12740755 -0.53186226 -0.04335356]
 [ 0.64824319  0.3808291  -0.87813687 -0.28606343  0.7092855   0.30556369
  -0.37343311  0.19230628  0.91141629 -0.99441814]
 [ 0.76022744 -0.01165318 -0.79493237  0.41822076  0.51319218  0.32334471
   0.98885846  0.11100173 -0.85208106  0.26295304]
 [-0.71011019 -0.9679718  -0.32678986  0.36189032 -0.71350431 -0.63158751
   0.76638818  0.23931861 -0.37095833 -0.84048557]
 [-0.55133247  0.53780198 -0.67556119 -0.12662482  0.02922988 -0.96926141
   0.67065406  0.82795072 -0.41323805 -0.7376678 ]
 [ 0.05176353 -0.8381753  -0.79019547  0.37744546 -0.56018686  0.69880033
  -0.2369802   0.2512114   0.76013947  0.42092705]
 [ 0.29867768  0.3647089  -0.08300138 -0.56301904  0.16217613 -0.24444103
  -0.07246351 -0.4804852   0.25434518 -0.6795969 ]
 [-0.33194089  0.87319827  0.2266233   0.97883606  0.95746088 -0.99121714
   0.60725546 -0.2594831   0.77461576  0.25920606]
 [-0.64279556  0.13874698  0.56704402  0.19232464 -0.66687822 -0.00693417
  -0.16051269  0.76022243  0.24708843 -0.82646346]
 [ 0.18449402  0.33861756  0.16553259  0.60852623 -0.10023761  0.72201872
  -0.5360527   0.74935722  0.28408647  0.87149811]]
3000 0.665913 [[-0.43925953  0.39654946  0.75850129  0.46155906  0.49158907 -0.73411608
   0.92117572  0.14414692  0.19505286  0.56225944]
 [-0.19095635 -0.47052455 -0.07899547  0.92174292  0.37236238 -0.03722787
   0.9969368  -0.49113226 -0.28499675  0.12402487]
 [-0.89337802  0.52696347  0.97484517  0.90222621  0.33551431 -0.60604048
   0.78848886 -0.8544662   0.05395889  0.98471951]
 [-0.41830897 -0.83323026  0.55251837 -0.02732611 -0.98443961  0.74806094
  -0.9536221   0.60010004  0.58222556 -0.11899447]
 [-0.19168067  0.31838632 -0.55445719  0.15315843 -0.64731288  0.95715165
  -0.5809834  -0.17919064  0.66809273 -0.38952017]
 [ 0.08074236  0.77345085 -0.82865477 -0.12224722  0.24851894  0.49926257
  -0.93379998 -0.67235923  0.71380305 -0.40337038]
 [ 0.58041739 -0.16755199  0.75980902  0.52284431 -0.77832699  0.56391907
  -0.65236187  0.03742433  0.19807673 -0.86889815]] [[ 0.03844428 -0.61687589  0.77105546 -0.53429389  0.43078113 -0.51339889
  -0.86045003 -0.12740755 -0.53186226 -0.04335356]
 [ 0.64824319  0.3808291  -0.87813687 -0.28606343  0.7092855   0.30556369
  -0.37343311  0.19230628  0.91141629 -0.99441814]
 [ 0.76022744 -0.01165318 -0.79493237  0.41822076  0.51319218  0.32334471
   0.98885846  0.11100173 -0.85208106  0.26295304]
 [-0.71011019 -0.9679718  -0.32678986  0.36189032 -0.71350431 -0.63158751
   0.76638818  0.23931861 -0.37095833 -0.84048557]
 [-0.55133247  0.53780198 -0.67556119 -0.12662482  0.02922988 -0.96926141
   0.67065406  0.82795072 -0.41323805 -0.7376678 ]
 [ 0.05176353 -0.8381753  -0.79019547  0.37744546 -0.56018686  0.69880033
  -0.2369802   0.2512114   0.76013947  0.42092705]
 [ 0.29867768  0.3647089  -0.08300138 -0.56301904  0.16217613 -0.24444103
  -0.07246351 -0.4804852   0.25434518 -0.6795969 ]
 [-0.33194089  0.87319827  0.2266233   0.97883606  0.95746088 -0.99121714
   0.60725546 -0.2594831   0.77461576  0.25920606]
 [-0.64279556  0.13874698  0.56704402  0.19232464 -0.66687822 -0.00693417
  -0.16051269  0.76022243  0.24708843 -0.82646346]
 [ 0.18449402  0.33861756  0.16553259  0.60852623 -0.10023761  0.72201872
  -0.5360527   0.74935722  0.28408647  0.87149811]]

In [6]:
lst_predict = list(predict)
lst_predict2 = []
for i in lst_predict:
    lst_predict2.append(i[0])
lst_predict2
test_data["Survived"] = pd.Series(lst_predict2, dtype="int64")
test_data = pd.DataFrame(test_data, columns=["PassengerId", "Survived"])
test_data.to_csv("tensorflow_hl20.csv", index=False)

test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 2 columns):
PassengerId    418 non-null int64
Survived       418 non-null int64
dtypes: int64(2)
memory usage: 6.6 KB